<?php
/**
 * WHITENESS - A Demo Magento Theme
 * Written for .net Magazine November 2011
 *
 * http://github.com/edvanbeinum/whiteness
 *
 * @author Ed van Beinum <e@edvanbeinum.com>
 */

/**
 * @var Mage_Catalog_Block_Product_New $this
 */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>

<!-- Add own own title -->
<h2 class="subtitle"><?php echo $this->__('Just Delivered!') ?></h2>

<?php $_columnCount = $this->getColumnCount(); ?>
<?php $i = 0;
    foreach ($_products->getItems() as $_product): ?>

        <div class="row new-product-row <?php if($i == 0) echo "first"; ?>">

        <div class="span5">
            <a href="<?php echo $_product->getProductUrl() ?>"
               title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img
                    src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280) ?>"
                    width="280" height="280" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/></a>


        </div>

        <div class="span5">
            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                        title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
            </h3>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <?php echo $this->getPriceHtml($_product, true, '-new') ?>

            <?php if ($_product->isSaleable()): ?>
            <button type="button" class="btn primary" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <ul class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>"
                       class="btn link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                <li><a href="<?php echo $_compareUrl ?>"
                                                        class="btn link-compare"><?php echo $this->__('Add to Compare') ?></a>
                </li>
                <?php endif; ?>
            </ul>
        </div>

        </div>
        <?php $i++; ?>
    <?php endforeach; ?>
<?php endif; ?>
