<?php
/**
 * WHITENESS - A Demo Magento Theme
 * Written for .net Magazine November 2011
 *
 * http://github.com/edvanbeinum/whiteness
 *
 * @author Ed van Beinum <e@edvanbeinum.com>
 */
?>
<!doctype html>
        
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>

<!--Add a container class which Twitter Bootstrap uses -->
<div class="container">

    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('breadcrumbsContainer') ?>
        <!-- Add Twitter Bootstrap row class -->
        <div class="main row col2-right-layout">
            <!-- Add Twitter Bootstrap span-two-thirds class -->
            <div class="col-main span-two-thirds">
                <?php echo $this->getChildHtml('content') ?>
            </div>
            <!-- Add Twitter Bootstrap span-one-third class -->
            <div class="col-right sidebar span-one-third"><?php echo $this->getChildHtml('right') ?></div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>

<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>